# Generated by Django 4.2 on 2023-06-04 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_main_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_discriptions', models.TextField()),
                ('file', models.FileField(upload_to='courses-files')),
            ],
            options={
                'verbose_name': 'Pdf',
                'verbose_name_plural': 'Pdf',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('redirect_id', models.IntegerField(blank=True, null=True)),
                ('redirect_path', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_done', models.BooleanField(blank=True, default=False, null=True)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('courses_pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.courses_pdf')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payments',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
