# Generated by Django 4.2 on 2023-06-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_courses_pdf_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course_discriptions', models.TextField()),
            ],
            options={
                'verbose_name': 'Our Corses',
                'verbose_name_plural': 'Our Corses',
            },
        ),
        migrations.RemoveField(
            model_name='courses_pdf',
            name='file_discriptions',
        ),
        migrations.AddField(
            model_name='courses_pdf',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.our_courses'),
        ),
    ]
