# Generated by Django 4.2 on 2023-06-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_audios_book_delete_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses_pdf',
            name='file_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
